### ISSUE TITLE
Add isFulfilled and isRejected for PromiseSettledResult[]

### ISSUE THREAD

**Issue by tychenjiajun** [sindresorhus/ts-extras#30]

**Comment by sindresorhus** [comment]
I don't intent to modify built-in methods here. We could make a similar method to `Promise.allSettled`, but is it really worth the overhead of having to import a method just for this?

**Comment by tychenjiajun** [comment]
@sindresorhus What about adding a method `hasOwn`?
```typescript
function hasOwn<Key extends PropertyKey>(key: Key) {
  return function <ObjectType>(object: ObjectType): object is Extract<ObjectType, Record<Key, unknown>> {
    return objectHasOwn(object, key);
  }
}

const results: PromiseSettledResult<string>[] = [{ status: 'fulfilled', value: 'foo' }]

const r = results.filter(hasOwn('value'));
```

https://www.typescriptlang.org/play?target=99#code/LAKAxg9gdgzgLgAgBYEMYILwIPICMBWApmHAHQAOAThHDQJ7mGmozYDuUACtY5XHQG5QoAGYBXKCQCW0BBALE4ACTTsoAHjxESAFQaEANAgDShOgkIAPOISgATdNwi9+pugD4AFKARyFJAC4cfzg9RgMfBABrMyC3CJAASiD5bUQpdC1FMMIEADIEACViCEo7dXiECSioCA53BABvSIB6FoQdbAARbCCAVRhcgAMskmZVDk9EoYQ2JFsEOBRKAHNCOCkoFYQAOQg7Jnx0AEYANlJIynWxSihkNFIwFAAbZ89UxSMYukShEABfYQgcSSDayD4kFSsDgAUWslBQJE0IRyRjcFmstgcCCcLjobi8kQhcCCo1C+gSvm+cTMCWSfjSCAyCDhcARSLJqKKJTKFVpVSgNTqUHcDWaIF8bQ63V6CAGwzJ42hUCmMzmCyWq3Wm22ewOpCOCDOFwlCCucBudxYjxeb2JXzMv1AgJAogk0lkGS6hBEm0I5R0XgAbi8xIQgjp6SHnmGmeg9lAdmJXihcM9COpA01Ltdbgho7GAIQYLBQZPPfIFAu5YtYCQHX1Qf1-F1u0EyK1oNx88xWGz2Rw8Qh8fFmLzUkyO7Om82WhAgj13ZFpHJeYmklH6enEuMs+GIuDL7IU7mQXmVaq1epiyK+Wd575Mu7Ev6+F2t4HusGd5U9jH97FcWHVwx08Cc3ESac71zO4F2-BAj10fQ1xCDcVy3FIQl3Vl2UPTkT2KM9ygvQUrxFG9TWgi082JKE1HeEIHR+V8EHfIFIFgRArhgZM4BgIInAAWwyQgAGV1jgdM7GKHjnkPeBKB1dwAG0AF1MAQZTGgQeAUAtfiEAAcnEZ5fVef1DKMasgmMiAIEM1jVPY6B4DNDTuN4mBSDMmxKE8Fh6MM6tDMSX4gA

**Comment by sindresorhus** [comment]
We have such method already.

**Comment by tychenjiajun** [comment]
> We have such method already.

Do you mean `objectHasOwn`? It doesn't work well with `Array.prototype.filter`:

```typescript

const has = Object.prototype.hasOwnProperty;

function objectHasOwn<ObjectType, Key extends PropertyKey>(
    object: ObjectType,
    key: Key,
): object is ObjectType & Record<Key, unknown> {
    // TODO: Use `Object.hasOwn()` when targeting Node.js 16.
    return has.call(object, key);
}
const results: PromiseSettledResult<string>[] = [{ status: 'fulfilled', value: 'foo' }, { status: 'rejected', reason: 'foo' }]

// typeof fulfilled is still PromiseSettledResult not PromiseFulfilledResult
const fulfilled = results.filter(r => objectHasOwn(r, 'value'));

function isFulfilled<T>(object: PromiseSettledResult<T>) {
    return objectHasOwn(object, 'value');
}

// typeof fulfilled2 is still PromiseSettledResult not PromiseFulfilledResult
const fulfilled2 = results.filter(isFulfilled);

```

The goal of `hasOwn` is adding type guard for `Array.prototype.filter`. It's not only a modify built-in method.

**Comment by jonahsnider** [comment]
That's not really an issue with `objectHasOwn` though. You should just make `isFulfilled` a type guard.

**Comment by tychenjiajun** [comment]
Thank you for your replies! @jonahsnider @sindresorhus I think https://github.com/robertmassaioli/ts-is-present is exactly what I want.
