### ISSUE TITLE
Proposal: better `arrayIncludes` and `setHas`

### ISSUE THREAD

**Issue by tychenjiajun** [sindresorhus/ts-extras#40]
The current implementation doesn't work as expected if the array and the item are not the same general type.

```ts
const arr = [1, 2] as const;
const b: string = '3';
if (arrayIncludes(arr, b)) { // expected to complain but not
    // do sth
}
``` 

I propose adding a generic type for `arrayIncludes` and `setHas` to provide type checking for the `item`.

```ts
function arrayIncludes<Type extends TItem, TItem = unknown>(
	array: Type[] | readonly Type[],
	item: TItem,
	fromIndex?: number,
): item is Type {
	return array.includes(item as Type, fromIndex);
}

const arr = [1,2] as const;
const foo: number = 3;
const bar: string = '3';
if (arrayIncludes(arr, foo)) { // works
    // if the type guard return true, foo is 1 | 2 here
}

if (arrayIncludes(arr, bar)) { // Type 'number' is not assignable to type 'string'.(2345)
}
```

[Playground link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwE6uQTwJKQDYgAmApgM4A8AKpgA7GLEAeUxYhpil2LAtgDSduxHogC8icAGswcAO5gAfAAoAUAEg0GTAC5OtYgG0AuogA+iVMWSEEeTHrrG+6mL11deztcFRweuEkYAfl0wEB4AI2JUZwBKXVdhRBgOajpEAG91SygQVCRNLAA6GHwiMiVEkWRU-QEfPwCmWIBuFQBfFRUIBFIoFHQxRAMARj4AJhMaxB6wPrbZvsQI3SkZeSHxtphgRCVCnDKSUn30AQjY2MyVRFvljpUdvc0So4qL2KA)

**Comment by sindresorhus** [comment]
@younho9 Thoughts?

**Comment by younho9** [comment]
I agree to narrowing the type of `searchElement` from the `unknown` to the supertype of array element. It is very useful.

> supertypes absolutely should be allowed inputs to includes, but we lack a mechanism to allow this. 
>
> https://github.com/microsoft/TypeScript/issues/26255#issuecomment-736680802
