### ISSUE TITLE
Are we correctly handling `console.Console` in node `objectKeys(console)`?

### ISSUE THREAD

**Issue by devinrhode2** [sindresorhus/ts-extras#50]
Getting this error
> Argument of type 'Console' is not assignable to parameter of type 'Record<PropertyKey, unknown>'.
>   Index signature for type 'string' is missing in type 'Console'.ts(2345)

When writing this code:
```ts
objectKeys(console) // .forEach, .map, etc
```

[This led me to discover this node.js quirk](https://twitter.com/DevinRhode2/status/1513007830198112257):
```ts
Object.keys(console).includes('Console') === true
```

This was actually VERY GOOD that I discovered this quirk. So, by all means, this type seems great.

Despite my satisfaction, I think it deserves some extra analysis.

Technically, `Console` is absolutely present at runtime, and therefore, in some aspect, we may consider this typescript error not correct. Imagine, I already knew `console.Console` was a thing, already knew `Object.keys(console).includes('Console') === true`, and I am writing some code with the console, and I'm using `objectKeys` from `ts-extras`. I may be hoping, assuming, that my iteration INCLUDE this capitalized `Console` property. When I see an error regarding it, I may be surprised, and consider the typescript error itself to be incorrect diagnosis.

I had written my own [better-typed alternative to `Object.keys`](https://stackoverflow.com/a/65117465/565877):
```ts
const ObjectTyped = {
  keys: Object.keys as <T extends {}>(yourObject: T) => Array<keyof T>
}
```
I do not think my alternative is better overall, but in this specific scenario, in some way, it is more correct. Using my own `ObjectTyped.keys` did resolve the error around `console.Console`.

Just for fun, I tried using:
 - latest node: `v17.9.0`
 - latest `@types/node`: `v17.0.23`
 - latest vscode-insiders: `v1.67.0-insider`
 - latest `typescript@next`: `v4.7.0-dev.20220408`
 
And got the same error :)

**Comment by sindresorhus** [comment]
// @ifiokjr

**Comment by ifiokjr** [comment]
It seems to cause errors with any value declared from an interface.

```ts
import { objectKeys } from 'ts-extras';

interface MyInterface {
  some: string;
  value: number;
}

type MyType = {
  some: string;
  value: number;
};

declare const withInterface: MyInterface;
declare const withType: MyType;

objectKeys(withInterface); // => ❌ ERROR
objectKeys(withType); // => ✅ PASS 
```
