### ISSUE TITLE
Support for ClassicJS compiled TS projects

### ISSUE THREAD

**Issue by dreinon** [sindresorhus/ts-extras#56]
With the current tsconfig, only TS projects which compile to ES modules can use ts-extras.

This project could be extended to TS projectes which compile to ClassicJS adding a tsconfig.cjs.json, which extends the current tsconfig.json, but overwrites two properties in `compilerOptions`:
- `module: commonjs`
- `outDir: current_output/cjs`

I'll make a PR soon.

**Comment by sindresorhus** [comment]
I only intend to support ESM.
