### ISSUE TITLE
bug, objectEntries return undefined for optional props

### ISSUE THREAD

**Issue by eranhirsch** [sindresorhus/ts-extras#57]
objectEntries adds `| undefined` when passed an object with an optional field:
```ts
type Obj = {
  a?: string;
}

const x: Obj = {};
const y = objectEntries(x); // ['a', string | undefined][]
```

But this is wrong because the array would never have the value `['a', undefined]` in it.

The problem is that typescript types `Obj['a']` as `string | undefined` correctly because that would be the type you would get if you accessed the prop `a` on an object `Obj`; but `Object.entries` has different semantics as it doesn't access each //possible// prop to get it's value, it enumerates the existing ones. 

I think this could be fixed by adding `Required` on the type:
```ts
export const objectEntries = Object.entries as <Type extends Record<PropertyKey, unknown>>(value: Type) => Array<[ObjectKeys<Type>, Required<Type>[ObjectKeys<Type>]]>;
```

**Comment by sindresorhus** [comment]
That would mean that if you access `y[0][0]` on the above object, the TS type would be `'a'`, while at runtime, it would be crash because `y[0]` would be `undefined`.

If we could get the keys as a tuple, we could potentially return this type: `[(['a', string] | undefined)]`

**Comment by eranhirsch** [comment]
`y[0]` should be `['a', string] | undefined` so y[0][0] should be a typescript error.

**Comment by eranhirsch** [comment]
> https://stackoverflow.com/questions/72625430/how-can-i-get-tuple-type-from-object-with-array-of-keys

I dunno, doesn't this solve their problem?

```ts
type Out<T, X extends [...(keyof T)[]]> = { [K in keyof X]: T[X[K]] };

function keySelector<T, X extends readonly [...(keyof T)[]]>(obj: T, keys: X): Out<T, X> {
    // @ts-expect-error 
    return keys.map(key => obj[key])
}

const resultVariadicTuple2 = keySelector({ A: "a", B: "b", C: 'c', X: 'x'} as const, ['A', 'B'] as const)
```

Probably could be simplified, I played around with their playground link...
