### ISSUE TITLE
Object.groupBy is missing

### ISSUE THREAD

**Issue by sarimarton** [sindresorhus/ts-extras#60]
I'm just passing by to leave an issue as a reminder, as I notice there isn't one yet.

Sorry that I don't have time to contribute.

It would be great to have a better typing in cases like

```tsx
Object.groupBy([{ a: 5, b: 6 }, { a: 7, b: 8 }], x => x.a)
```

**Comment by kovacsaronlaszlo** [comment]
My solution is the following lines:
type ObjectGroupBy = <T, K extends PropertyKey | undefined>(
  items: Iterable<T>,
  keySelector: (item: T, index: number) => K
) => Record<Exclude<K, undefined>, T[]>

const objectGroupBy = Object.groupBy as ObjectGroupBy

**Comment by sarimarton** [comment]
sorry, invalid issue
