### ISSUE TITLE
Proposal: `safeCastTo`

### ISSUE THREAD

**Issue by Max10240** [sindresorhus/ts-extras#61]
Allow cast a value to the given type safely.

Possible use case:
[ts-playground](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABAZwIbAKYGFXKgFTgB58A+ACgDdUAbEDALkXwEpEBvRAJwyhC6TU6GANyIAvgChJMMFAxdgqCBkQAxOHA6TEiVEzxdZAcxE7EAIwD8TMCAC2FhWamSAJhgg1UPRBAR4iAAOcMjIMBY0GACqYB7AshhuTBpaAD6I4PGJbmaS-mCBwJqIALzBoeGRMXEYCWBJiGkZaJg4eIREAAo+sLREqaQU7OIsZgXIcFEAdDRwxuTFcNOoiFZWiADkmwA0iEvTFmsbAAxj0hNQlj5lFWERUbHZDW5NGSPjAVMYs-PkFj4VsctrtrlxDsCzmYAPTQ3TwhEIgB6KMQXS4cCCCigAE8tqhNog3HAMMhEGA4FcMAAPGCBBCIXFYrYjTbTcgAJgAzFyAJwsSSwxHCkWilFItEYrFcXFbCyE4mk8mUxA0ulXBlM1SbVns7l8gVAA)
```tsx
function safeCastTo<T>(value: T) { return value; }

interface Foo {
  a: string;
  b?: number;
}

declare const possibleUndefined: Foo | undefined;

const foo = possibleUndefined || safeCastTo<Partial<Foo>>({});
console.log(foo.a ?? '', foo.b ?? 0);

const bar = possibleUndefined || {};
console.log(bar.a ?? '', bar.b ?? 0);
//             ^^^ Property 'a' does not exist on type '{}'.(2339)
//                          ^^^ Property 'b' does not exist on type '{}'.(2339)


```

**Comment by sindresorhus** [comment]
Looks useful 👍
