### ISSUE TITLE
Support commonjs?

### ISSUE THREAD

**Issue by Max10240** [sindresorhus/ts-extras#62]
I know it's "going backwards",  but I have a lot of commonjs projects around me, especially work-related ones. 
Supporting only `esm` would even reduce my willingness to use it in `esm` type projects:  I would prefer to find a tool that works in both module types at the same time, rather than choosing "ts-extras" as my choice in `esm` environment and thinking what should I use in `cjs` environment.

ps: If support for "cjs" is desirable, I have the will to implement it

**Comment by sindresorhus** [comment]
Sorry, I have no plans to support CommonJS. I moved on years ago. However, the good news is that from Node.js 22, it's possible to `require` ESM modules from CommonJS: https://nodejs.org/en/blog/announcements/v22-release-announce#support-requireing-synchronous-esm-graphs

**Comment by marcus-sa** [comment]
You can also load esm modules in commonjs like this
```ts
async function dynamicImport<T>(id: string): Promise<T> {
  return await (new Function(`return import('${id}')`)() as Promise<T>);
}
```

**Comment by Max10240** [comment]
Sure, but it would force everything that uses `ts-extras` to be asynchronous, which is not what I expected. In contrast, I prefer the `--experimental-require-module` in `nodejs 22` (as @sindresorhus  mentioned), which allows me to use `ts-extras` in a non-intrusive way, as if it were itself a commonjs format package. Anyway, thanks for the advice

As an aside: I really like the "Runtime Types" idea of [deepkit](https://github.com/deepkit/deepkit-framework)!
